baseURL = "https://interkosmos.org/"
languageCode = "en-us"
title = "Interkosmos System"
theme = "archie"
copyright = "interkosmos.org"

[params]
  mode="auto"
  featherIconsCDN=true

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/interkosmos-org"

[[menu.main]]
name = "Archive"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Build"
url = "https://build.interkosmos.org"
weight = 4
